# Generated by Django 5.2.2 on 2025-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "imagefield",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("Last_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=191, null=True, unique=True
                    ),
                ),
                ("phonenumber", models.TextField(blank=True, null=True)),
                ("accept", models.BooleanField(default=False)),
            ],
        ),
    ]
