# Generated by Django 5.2.2 on 2025-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0002_attendencemark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencemark",
            name="join_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="attendencemark",
            name="leave_time",
            field=models.TimeField(),
        ),
    ]
