# Generated by Django 5.2.2 on 2025-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0003_alter_attendencemark_join_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendencemark",
            name="join_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendencemark",
            name="leave_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
